name: Flaky-Dev-Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  tests:
    runs-on: ${{ matrix.arrays.os }}
    strategy:
      matrix:
        arrays: [
          {os: ubuntu-22.04, python-version: '3.7.17'},
          {os: ubuntu-22.04, python-version: '3.8'},
          {os: ubuntu-22.04, python-version: '3.9'},
          {os: ubuntu-22.04, python-version: '3.10'},
          {os: ubuntu-22.04, python-version: '3.11'},
          {os: ubuntu-22.04, python-version: '3.12'},
          {os: ubuntu-22.04, python-version: '3.13'},
          {os: ubuntu-22.04, python-version: '3.14.0-rc.3'},
          {os: windows-latest, python-version: '3.7.9'},
          {os: windows-latest, python-version: '3.8'},
          {os: windows-latest, python-version: '3.9'},
          {os: windows-latest, python-version: '3.10'},
          {os: windows-latest, python-version: '3.11'},
          {os: windows-latest, python-version: '3.12'},
          {os: windows-latest, python-version: '3.13'},
          {os: windows-latest, python-version: '3.14.0-rc.3'}
        ]
    steps:
      - name: Set up Python ${{ matrix.arrays.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.arrays.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest-cov ipython notebook==6.2.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test with pytest
        env:
          PYTHONHASHSEED: 1
          PYTEST_RUN_PERF_TESTS: 1
        run: |
            python -Xfrozen_modules=off -m pytest -vv tests/test_fast_capped_str_casts.py::test_speed

